[package]
name = "my_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = { version = ">=1.8.0", features = ["union", "const_generics"] }

[profile.dev]
panic = "abort"

[profile.release]
lto = "fat"
panic = "abort"
